package edu.nju.umr.po.enums;

public enum POKind {
	ACCOUNT,CITIES,CITY,CONSTANT,COUNT,DIARY,DRIVER,GOOD,ORG,SHELF,STOCK,USER,VAN,WORK,ARRIVE,
	CENTERLOADING,EXPRESS,HALLLOADING,INCOME,ORDER,PAYMENT,RECIPIENT,SEND,STOCKIN,STOCKOUT,TRANSIT,
	TRANSITINFO
}